### ISSUE TITLE
Reformat code to meet http://standardjs.com/

### ISSUE THREAD

**Issue by lliss** [ProboCI/probo#100]
This is more of a proposal than an actual issue.

I would like to suggest that over time we move our projects to follow a set standard... http://standardjs.com/

While it is true there are aspects of the code we would have to adjust and that there are parts of the standard we might not actually like, I think the rules are quite good and sensible. The added advantage is that we don't have to maintain and enforce our own standard and maintain eslint files which is not something I find to be either rewarding, enjoyable, or a particularly good investment of time.

I'm not suggesting that we move everything at once, but some of the smaller projects could be converted pretty quickly, I'd guess, and over a few months of PRs, I'm sure the others would get sorted out pretty easily as well.

**Comment by tortillaj** [comment]
Not going to do this
