### ISSUE TITLE
Allow $table_prefix to be configurable in the Wordpress plugin

### ISSUE THREAD

**Issue by brianyoungblood** [ProboCI/probo#105]
Most Wordpress sites have custom MySQL table prefixes other than those starting with "wp_". Ideally the constant for $table_prefix should be allowed to be changed in the probo.yml possibly the same way the databaseName is configurable.

The example config here https://docs.probo.ci/plugins/wordpress-plugin/ would change to something like:

    
      assets:
        - dev.sql.gz
        steps:
        - name: Site setup
          plugin: WordPressApp
          database: dev.sql.gz
          databaseName: wordpress
          tablePrefix: wp_abcxyz
          databaseGzipped: true
          subDirectory: code
          devDomain: example.com
          devHome: example.com/home
        - name: Flush the cache
          plugin: WordPressApp
          flushCaches: true

**Comment by sk33lz** [comment]
The initial work for this was merged in PR #116. 

There is apparently a bug that was introduced that is currently being tested in PR #132.

**Comment by tortillaj** [comment]
See #133
