### ISSUE TITLE
Drupal plugin should respect the databaseName option

### ISSUE THREAD

**Issue by dearmond** [ProboCI/probo#108]
https://github.com/ProboCI/probo/blob/master/lib/plugins/TaskRunner/Drupal.js#L37

It pulls from constants instead of from the LAMPApp options.

**Comment by dearmond** [comment]
Pull request: https://github.com/ProboCI/probo/pull/109

**Comment by jodyHamilton** [comment]
Handled in https://github.com/ProboCI/probo/pull/150
