### ISSUE TITLE
drush make --force-complete option should be optional

### ISSUE THREAD

**Issue by joeparsons** [ProboCI/probo#137]
The `--force-complete` option for drush make is currently [hard-coded](https://github.com/ProboCI/probo/blob/master/lib/plugins/TaskRunner/Drupal.js#L209) into the Drupal Probo plugin.

This causes problems for us because, if we introduce a breaking change to our drush make file, the Drupal plugin step in our Probo CI build configuration still reports as "successful" even though drush make had problems and then our other Probo.CI config steps have problems due to missing modules, etc.  The underlying problem is that the `--force-complete` option for drush make generates drush warnings but does not exit with an error status, which would be preferable for our purposes.

We would prefer for the hard-coded `--force-complete` to be be removed from the Drupal plugin and possibly even the addition of a `makeArgs` option that could be used to provide drush make options.

**Comment by sk33lz** [comment]
This fix was merged today. Thanks @joeparsons!
