### ISSUE TITLE
Builds are sometimes indicated "reaped" when I visit them at first.

### ISSUE THREAD

**Issue by dzink** [ProboCI/probo#214]
Refreshing the build page (not the build itself, but inside the web app) will fix the problem.

**Comment by ElusiveMind** [comment]
It could be you are looking at the build page of an older build and not the latest build. This can be confusing, but if the build is re-built while you are on a build page, that one will be outdated and you will need to go back to the dashboard to get the latest build page link. Interface improvements will help with this which are in development.
