### ISSUE TITLE
Reduce clutter in probo GitHub hook.

### ISSUE THREAD

**Issue by dkinzer** [ProboCI/probo#22]
There is a an action item for every probo step in the check details panel on Github PRs.  This seems to be unnecessarily verbose, especially when contrasted to similar services that only post one link (or limit the number of posts to actual full runs):

![2015-12-10_08-46-42](https://cloud.githubusercontent.com/assets/444215/11716917/10b9de60-9f1b-11e5-8eca-6d40c2feab7a.png)

**Comment by tizzo** [comment]
So first off - I totally agree and I'm actually working on tidying that up in PR #11 (the details might be a bit inside baseball ATM but I'm restructuring the whole step iteration process to make it cleaner way more flexible and adding a bunch of features. This is going to include a step list that you can use to roll a bunch of steps into one.

Second, there's a couple of things you can do to decrease the work you need to do.

The first is to use the [Drupal plugin](http://probo.ci/docs/drupal-quickstart/) (please do see [the code](https://github.com/ProboCI/probo/blob/master/lib/plugins/TaskRunner/Drupal.js) if you're curious about exactly what it does, I think it's fairly readable).  This automates a bunch of the things I think you're doing here.

The second is to put all of your steps in a bash script in the repo and have one step run that.

The third is to use the undocumented [`Script` plugin](https://github.com/ProboCI/probo/blob/master/lib/plugins/TaskRunner/Script.js) to combine your steps. In any line fails I believe the entire thing will abort.

The following would work:

```` yaml
steps:
  - name: Do all of the things!
    script:
      - echo "I'm the first thing!"
      - echo "I'm the second thing!"
````

**Comment by dkinzer** [comment]
Thanks, but in the mean time I've noticed that PRs aren't getting links from probo anymore is this a new issue?

**Comment by tizzo** [comment]
Not one that we've seen on our projects - could you link me to a PR or push that didn't get a link?

**Comment by dkinzer** [comment]
Sure, here's one: https://github.com/NuCivic/dkan/pull/828
