### ISSUE TITLE
Sometimes docker API calls fail with EPIPE error

### ISSUE THREAD

**Issue by zanchin** [ProboCI/probo#28]
This is due to a node 4.1.2+ change that broke how node handles unix sockets closing their connections prematurely. Creating this issue to track upstream:

Node issue (where fix will happen): https://github.com/nodejs/node/issues/3947
Dockerode issue: https://github.com/apocas/dockerode/issues/193

**Comment by ElusiveMind** [comment]
This seems to be resolved upstream
