### ISSUE TITLE
Rebuild from probo interface

### ISSUE THREAD

**Issue by dafeder** [ProboCI/probo#33]
There are often scenarios in which we'd want to rebuild manually. For instance, a build dependency has changed but the main repo has not. Most CI tools have a button to re-do the build using the same parameters. This would be a great addition.

**Comment by AlexU-A** [comment]
This is in the near term roadmap, so stay tuned for more info!

**Comment by greggles** [comment]
FWIW: The workaround I know is:

> git commit --amend -m"Some slightly different message" ; git push -f origin BRANCHNAME

And subscribe :)

**Comment by zanchin** [comment]
You can also (right now) just edit the PR by changing a label or assignee, which will trigger a build.

**Comment by tortillaj** [comment]
@dafeder - you may well be aware now, but in case not, there is now a rebuild link in the Probo interface: 
![probo-rebuild-link](https://cloud.githubusercontent.com/assets/851788/14235115/c234754a-f9c2-11e5-947c-34e1ca917108.png)

**Comment by dafeder** [comment]
Great! Haven't had a chance to use it yet but looking forward to it :)
