### ISSUE TITLE
Include repo and branch name in subdomain

### ISSUE THREAD

**Issue by dafeder** [ProboCI/probo#34]
At least for us, our development process often involves working on several branches and repos during a single session of work. In our homegrown QA system (which we're trying to replace with Probo), sites get a subdomain for the repo they're built from and a sub-subdomain for the branch name. Probo's domain names are just a hash and I've often been confused about what build I'm actually looking at. 

IE,

http://my-branch-name.repo.our-qa-server.com

vs

https://99a085dd-041d-419d-9bb7-bffe54ccb52c.probo.build

**Comment by tizzo** [comment]
So two things - the first is that in the hosted version of probo we do have a link right now that provides *some* additional context but it's just the PR number. That link has the project id (another pseudo random guid thingy) and the pr number. That will always point to the most recent build for that PR even if new changes get pushed.  The other link (which we're calling the `permalink`) points to the guid of that build so it's specific to that commit essentially.

![probo links explained](https://cloud.githubusercontent.com/assets/245728/12328757/e2a4dc04-baaa-11e5-9655-8f952e02448b.png)

Doing some nicer aliases is in our backlog. I'm hesitant to 

As for probo as an open source project - the [proxy lookup logic](https://github.com/ProboCI/probo-proxy/blob/master/lib/proxy-lookup.js) probably needs some love to allow more flexible aliasing before this could be cooked up by people at home. I think we may be making this more pluggable as we move forward, it's definitely toward the top of our backlog but we have a few other things in front of it inline.

**Comment by dafeder** [comment]
Ahh, all good points I hadn't considered. I think with lets encrypt they have a process that once your domain is whitelisted you can create new certs for subdomains instantly, but I haven't played with it yet. Even then the volume of new certs an app like this produces might be seen as abuse.

For now I'm going to try to add something to the build process that adds this info to the visible site pages.

**Comment by tizzo** [comment]
Yeah, I've been thinking of adding documentation (or maybe even automated
integration) for environment indicator
<https://drupal.org/project/environment_indicator> module to provide more
context.
