### ISSUE TITLE
Don't always append Drupal $databases array

### ISSUE THREAD

**Issue by bjeavons** [ProboCI/probo#37]
No matter if `this.options.siteFolder` /settings.php exists or not a default $databases array is written there which means Drupal DB prefixing is unsupported. See https://github.com/ProboCI/probo/blob/master/lib/plugins/TaskRunner/Drupal.js#L108

How can prefixing be supported within Probo? 

A couple options:
1. plugin option for specifying prefix e.g. `this.options.dbPrefix`
2. plugin option for skipping default db array write e.g. `this.options.useOwnSettings`

I prefer option 2 because it allows more control over the full databases array. Its more of an advanced option so would mean that if the committed settings.php file was missing `$databases` tho that the step would fail.

**Comment by bjeavons** [comment]
https://github.com/ProboCI/probo/issues/37 would definitely work for us too

**Comment by tizzo** [comment]
Given @bjeavons thought that providing a required file would fix the issue and the even better arbitrary snippet solution, I'm marking this closed.  Feel free to reopen if there's a use case I haven't thought of.
