### ISSUE TITLE
Branch building

### ISSUE THREAD

**Issue by xendk** [ProboCI/probo#44]
We're exited about Probo, but one worry is that it only builds PRs. We're used to every branch being build on push, as is common.

Any plans for branch building? If not build-all-branches, then at least being able to configure `develop` to always being build?

**Comment by tizzo** [comment]
Yep, we're planning to add branch building in the very near future. I'll update this issue as that effort progresses.

**Comment by xendk** [comment]
Excellent! Keep up the good work.

**Comment by sean-dietrich** [comment]
I am curious has there been any further development on this?

**Comment by thom8** [comment]
Also very keen on this feature however as a workaround after each release we push an empty commit to `develop` and start a new "Next release" PR.

`git -m"Build next release." --allow-empty`

**Comment by Auspicus** [comment]
Bump. Would be really useful for us. We are using Percy on a per branch basis but it would be great to have `master` get built in Probo and run Percy after each deploy to generate a new baseline.

**Comment by ElusiveMind** [comment]
This is possible on Probo 2 by adding [build] to your commit message. Will build a build for that commit.-
