### ISSUE TITLE
Provide bower pre-installed on base image

### ISSUE THREAD

**Issue by mike-roberts** [ProboCI/probo#48]
Since bower is usually globally installed by `npm install -g bower` can that be provided in the base image, rather than having to install it through the yaml file?

**Comment by mike-roberts** [comment]
And also gulp-cli as well?

**Comment by mike-roberts** [comment]
Also latest version of node is the LTS release which is v4.3.0 and probo.ci machine is running v0.10.41

**Comment by tizzo** [comment]
Sorry for the slow response - yeah, in general the image uses what you get in a default install on ubuntu 14.04. We're trying to optimize for serving the majority case and *not* including the kitchen sink.  That said, bower, gulp, and grunt are all widely used and node 0.10 is pretty ancient in node years. We run the latest 4.x on all of our other stuff.  We'll be updating the image to at least have a newer node (we'll probably standardize on latest stable).

**Comment by mike-roberts** [comment]
:+1: Yeah, all this stuff is pretty easy to workaround right now since we can just run shell commands from our yaml config. More recent node would be nice to have on all the machines though :smile:

**Comment by sk33lz** [comment]
Our latest docker images tagged with -nightly on the end include the node 4.x branch. See https://github.com/ProboCI/probo-image-builder/blob/master/ansible/roles/ubuntu-nodejs/tasks/main.yml#L10 for the source. Please try one of the following images below to use node 4.x out of the box:

```
proboci/ubuntu-14.04-lamp:php7.1-nightly
proboci/ubuntu-14.04-lamp:php7.0-nightly
proboci/ubuntu-14.04-lamp:php5.6-nightly
```

We also have some built some experimental 16.04 images that we are still doing some testing on that you are welcome to take for a spin. They should include the same packages. See the currently whitelisted 16.04 images below:

```
proboci/ubuntu-16.04-lamp:php7.2-nightly
proboci/ubuntu-16.04-lamp:php7.1-nightly
proboci/ubuntu-16.04-lamp:php7.0-nightly
```

It doesn't currently look like we are including bower or gulp out of the box yet, so I'll get those added and tested in my next round up updates to nightly builds. So far they aren't quite "nightly" yet, but will be soon enough. 

I'm in the process of compiling a list of the available software versions and available packages for each image in the newly created Docker Images section of Probo Docs. There will be a blog post available to highlight the new features soon. I'll update here also.

We appreciate your feedback. I'll let you know when the nightly images will be ready to test for bower and gulp.

**Note:** Feel free to request additional software packages that aren't currently included in our docker images by opening an ticket with the feature request. We will probably add it if it's something we feel is a useful addition to the Probo testing stack.

**Comment by greggles** [comment]
Thanks, @sk33lz and probo team!

I tried this out and it reduced a step from ~35 seconds to ~15 seconds. That's not a ton on its own, but every bit helps :) 

The rest of the build ran as normal, fwiw (i.e. I don't see any major bugs with the nightly).

**Comment by sk33lz** [comment]
That's great @greggles! Thanks for the update. What image did you end up using?

We were pushing hard to get these new images out before Thanksgiving, and technically did. We didn't announce them officially yet, as we wanted to get a few of these new pieces in and tested more thoroughly. 

Thanks for helping test the new images out and providing additional feedback Greg!

**Comment by greggles** [comment]
That was using proboci/ubuntu-14.04-lamp:php7.0-nightly.

**Comment by sk33lz** [comment]
Closing this out as bower is available in the nightly images and will also be available in the new base image after the Probo Image Restructure is deployed.
