### ISSUE TITLE
Adding Github label to PR shouldn't rebuild probo

### ISSUE THREAD

**Issue by allisondev** [ProboCI/probo#52]
When I add a Github label to a PR that already had a probo site spinned up, the labeling causes probo to rebuild. If someone was testing with the first probo build, and someone else added a label to the PR, then the tester's work would get wiped out and that shouldn't happen. 

Steps to reproduce:
- Create a Github PR for a repo using probo
- Wait for the probo build on the PR to complete successfully
- Then add a Github Label to that PR

Actual Result:
- See that probo rebuilds (wiping out the probo site build previously created)

Expected Result: 
- Probo shouldn't rebuild for that PR because no commits or changes were made to the PR.

**Comment by tizzo** [comment]
Yep, that's a known issue and we're working on it - currently this is a helpful workaround people are using to trigger rebuilds until we get the rebuild button into the UI.

**Comment by allisondev** [comment]
Gotcha, thanks! I didn't see the issue created so made this one. 
Interesting workaround -- but can't you also close and reopen the PR to trigger rebuild? It's just one extra click.

**Comment by tortillaj** [comment]
@allisondev I believe this issue that you posted was resolved. Thanks for notifying us here!

**Comment by allisondev** [comment]
Thanks!
