### ISSUE TITLE
BitBucket Pull Request Build Step never finishes

### ISSUE THREAD

**Issue by humansky** [ProboCI/probo#62]
Every BitBucket Pull Request has a step that indicates it never finishes

![screen shot 2016-04-13 at 11 21 04 am](https://cloud.githubusercontent.com/assets/184953/14498830/fe62d3e6-0169-11e6-8271-e7ba50a20755.png)

The BitbucketDownloader task is never marked as complete, despite all the other steps completing successfully.

**Comment by tizzo** [comment]
I think this is resolved. Let me know if you see it again.
