### ISSUE TITLE
Provide for Drupal 8's trusted_hosts setting

### ISSUE THREAD

**Issue by tizzo** [ProboCI/probo#63]
In Drupal 8 there's a new setting called [`trusted_hosts`](https://www.drupal.org/node/2410395). This is interfering with probo builds. We should consider having the Drupal plugin append a snippet in `settings.php` for Drupal 8 sites like:

``` php
$settings['trusted_host_patterns'] = array(
  '^localhost$',
  '^.+\.probo\.build$',
);
```

**Comment by heddn** [comment]
If you do what  platform.sh does, you can reference & include a settings.probo.php based on the existence of an environment variable. Then insert the hostname dynamically as well.

**Comment by sk33lz** [comment]
See https://github.com/platformsh/platformsh-example-drupal8/blob/master/scripts/platformsh/dist.settings.php#L35.

**Comment by greggles** [comment]
For anyone else who finds this, a potential solution today is using the `settingsAppend` feature [of the Drupal plugin](https://docs.probo.ci/plugins/drupal-plugin/):

```
    settingsAppend: |
      $settings['trusted_host_patterns'] = array(
        '^localhost$',
        '^.+\.probo\.build$',
      );
```
