### ISSUE TITLE
Support the color in the web app terminal

### ISSUE THREAD

**Issue by quicksketch** [ProboCI/probo#66]
When running a Backdrop (or Drupal) SimpleTest suite, the `--color` option is quite helpful to quickly find failures in the terminal output. In the web UI for Probo, the colors are not decoded and instead display as their escape characters:

```
[32mActions: Actions executing in a potentially infinite loop (ActionLoopTestCase) 13 passes, 0 fails, 0 exceptions, and 1 debug message
[0m[32mAJAX: AJAX forms on cached pages (AJAXFormPageCacheTestCase) 33 passes, 0 fails, 0 exceptions, and 10 debug messages
[0m[31mAdministration bar: Link types (AdminBarLinkTypesTestCase) 21 passes, 0 fails, 3 exceptions, and 4 debug messages
[0m[32mBatch API: Batch percentages (BatchPercentagesUnitTestCase) 18 passes, 0 fails, and 0 exceptions
```

Something like this might help: http://pablomarin-garcia.blogspot.com/2011/04/converting-ansi-to-html-how-to-convert.html

**Comment by tizzo** [comment]
Yes, this! We're planning to use [ansi-to-html](https://www.npmjs.com/package/ansi-to-html) from npm. It's been on my TODO list for a while but it should be a pretty trivial change - I'll bump it up my priority list.

**Comment by tizzo** [comment]
Just updating to say that we have a PR in progress to add this. 💃

**Comment by quicksketch** [comment]
Woo, great thanks @tizzo!

**Comment by tizzo** [comment]
This is live! Colors galore!
