### ISSUE TITLE
Whitespace removed from web UI terminal

### ISSUE THREAD

**Issue by quicksketch** [ProboCI/probo#67]
The white space from the terminal output in the web UI seems to be collapsed. My local output looks like this:
```
Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
```

But Probo's UI is missing the spaces:

```
 Status Group Filename Line Function
-------------------------------------------------------------------------------- 
```

**Comment by tizzo** [comment]
Ah, that's interesting… I'm not sure (off the top of my head) what might be causing that. We pipe the raw output bytes from docker's output straight into a rethinkdb database and then put the raw contents on the screen.  I wonder if this could have something to do with the tty buffer size causing the library to layout things differently or if there's some kind of tabbing that's not working the same way between `<pre>` tags.

I'll need to dig a bit deeper.

**Comment by tizzo** [comment]
We have a PR just about ready to fix this!

**Comment by tizzo** [comment]
So sorry for the slow response - we needed to do a little work and testing on the security and performance side and have had a lot going on. This is now live! Please let me know how it looks!
