### ISSUE TITLE
Redirect properly after login

### ISSUE THREAD

**Issue by dafeder** [ProboCI/probo#70]
Minor issue: If I follow a link to a build from Github and am not logged into Probo, it takes me to a login screen and then just takes us to my top-level list of projects rather than the build I originally clicked on. Not a big deal at all, I go back to the PR on Github and click through again. But it does happen to me once a day or so, and for people new to the service it is often confusing.

**Comment by tizzo** [comment]
I believe this has been resolved - please let me know if you see the issue again!
