### ISSUE TITLE
Multisite Support

### ISSUE THREAD

**Issue by dearmond** [ProboCI/probo#72]
When running tests, I would like to have several different Drupal installs. The use case for this is I want to test an install profile with a couple different sql dumps, plus a fresh install. Each one would be a different "siteFolder".

The way I see this working is by simply entering "siteFolder: site1" into the Drupal plugin that it creates a multisite setup so that the url is: https://site1.UUID.probo.build.

Then, in the same .probo.yaml file, I could add a second Drupal site install for "siteFolder: site2".

**Comment by tizzo** [comment]
Hey, sorry for the slow response!

We have most of the framework for good multi-site handling already. We want to be secure by default, so we don't want to introduce a new level of subdomain (be use wildcard certs) so instead we support suffixes (a letsencrypt scheme has been researched and deemed untenable at present).

You can currently use any `https://[uuid]--site-[anything].probo.build` and that will properly resolve to your container and then you just need to either have site folders or a `sites.php` file to match. I just reviewed our `Drupal` plugin and it wouldn't take much to make it really support multi-site as a first class citizen.  I think it could automatically generate your sites.php and it could setup and import multiple databases - the one tricky bit is how we give you links to the different sites. We don't really have a good place to put it in the UI at present.

**Comment by brianyoungblood** [comment]
@tizzo would the tokens be used in the probo.yaml? I have one site with 4 urls configured to show content - each probo url would need site-one.probo.build, site-two.probo.build and all should be  routed to the same instance. Hoping this made since. I discussed with @grndlvl and said I'd post a comment here.

> You can currently use any https://[uuid]--site-[anything].probo.build and that will properly resolve to your container and then you just need to either have site folders or a sites.php file to match

**Comment by brianyoungblood** [comment]
this answers my question and is working for us. not a polished example, but may be helpful for someone else coming this way.

[https://gist.github.com/brianyoungblood/583fb75a90e55b55bba5460ca3a639e4](https://gist.github.com/brianyoungblood/583fb75a90e55b55bba5460ca3a639e4)

**Comment by ElusiveMind** [comment]
This is also covered here:
https://docs.probo.ci/drupal/multisite/
