### ISSUE TITLE
Provide more context in build environment variables

### ISSUE THREAD

**Issue by tizzo** [ProboCI/probo#75]
Currently [we provide](https://github.com/ProboCI/probo/blob/master/lib/Container.js#L191) a set of environment variables in builds but they are somewhat incomplete. We provide the commit that was built but not the branch it belonged to - we should add this and evaluate what other metadata we can/should provide.

**Comment by ElusiveMind** [comment]
The branch name and a link to the branch and pull request are currently part of every build. Future enhancements should be included in subsequent tickets with more detail as to the specific requests.
