### ISSUE TITLE
databaseName is not respected in Wordpress plugin

### ISSUE THREAD

**Issue by lliss** [ProboCI/probo#90]
https://github.com/ProboCI/probo/blob/master/lib/plugins/TaskRunner/WordPressApp.js#L78
https://github.com/ProboCI/probo/blob/master/lib/plugins/TaskRunner/WordPressApp.js#L27

The actual database name that is used when building is hard coded.

**Comment by dearmond** [comment]
This appears to be fixed now:
https://github.com/ProboCI/probo/blob/master/lib/plugins/TaskRunner/WordPressApp.js#L39

**Comment by lliss** [comment]
Correct. Thanks.
Fixed by https://github.com/ProboCI/probo/pull/93
